### ISSUE TITLE
Add a maximum version to pytest dependency for the pytest extra

### ISSUE THREAD

**Issue by adamtheturtle** [simplistix/sybil#137]
**Goal**

If a maximum version were added to the pytest version in the `pytest` `extras_require` section, this would give users a clearer and earlier understanding of why Sybil is not working when a `pytest` version update comes. At https://github.com/simplistix/sybil/issues/82#issuecomment-1914506697 I referred to the fact that Pytest 8 had been released and I had runtime errors. If there had been a `<8` pin, I would have got a clear error from `pip` that Sybil was not compatible with Pytest 8.

**Cons**

* If Sybil has Pytest pinned to <9, but is actually compatible with Pytest 9 when it comes out, then users will get an install error if they have both `sybil[pytest]` (latest) and `pytest==9.0.0` in their configuration, when it would actually work. A user could work around this by removing the `[pytest]` extra, or they could wait until an updated Sybil is released with a more relaxed Pytest pin.
* Maintenance of updating the pin with each (major?) release of Pytest, and as @cjw296 pointed out in https://github.com/simplistix/sybil/pull/130#issue-2527615951:

> I'll likely miss new major versions of pytest coming out, and I don't want to artificially pin either my own projects or others to an older version of pytest because of this

Not a con, but a comment...

From @cjw296 in https://github.com/simplistix/sybil/pull/130#issue-2527615951:

> I've been bitten too many times by pytest changing "internals" that packages like Sybil are forced to use in second or third point versions

I do not believe that pinning a major version increases or decreases the "being bitten" chances if Pytest makes a breaking change in a minor version. It simply does not affect that situation.

**Suggested steps**

To mitigate the cons, I suggest using tooling to automatically update the Pytest pin. The following is a workflow like what I use in my own projects, and could be done one small step at a time:

* Switch from `setup.py` to `pyproject.toml` for install. This is useful as tools such as Dependabot can work with `pyproject.toml`. An alternative is to use `requirements.txt` files and have `setup.py` read these.
* Add a dependabot configuration, something like:

```yaml
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  allow:
      - dependency-name: "pytest" # To optionally have dependabot work only on pytest
  groups: # Limit to only major versions (there may be a better way of doing this)
      pytest:
        applies-to: version-updates
        patterns:
          - "pytest"
        update-types: ["minor", "patch"]
```

* If desired, create a GitHub workflow automatically merge the dependabot PR if CI passes
* Pin pytest to <9 in the `pytest` `extras_require`.
